"""Executor: guards, timing, preview downscale, code generation."""
from __future__ import annotations

from typing import Any

import cv2
import numpy as np

from app.config import settings
from app.core.errors import OperationError
from app.core.logging import Timings
from app.ops.helpers import as_gray, require_binary, require_gray
from app.ops.registry import REGISTRY, Cost, OpContext, OpResult, OpSpec
from app.services.store import Entry, Session, Store


def _guard(spec: OpSpec, img: np.ndarray) -> None:
    if spec.needs_gray:
        require_gray(img, spec.cv)
    if spec.needs_binary:
        require_binary(img, spec.cv)
    if spec.needs_color and img.ndim == 2:
        raise OperationError(f"{spec.cv} needs a colour image.",
                             hint="Run 'Gray → BGR' first.")


def execute(store: Store, s: Session, op_id: str, raw_params: dict[str, Any] | None,
            *, image_id: str | None = None, preview: bool = False,
            image2_id: str | None = None) -> dict[str, Any]:
    spec = REGISTRY.get(op_id)
    p = spec.coerce_params(raw_params)
    t = Timings()

    with t.phase("load"):
        src_id = image_id or s.current.image_id
        src = store.img(s, src_id)
        img = src
        scale = 1.0
        if preview and spec.cost is Cost.EXPENSIVE:
            h, w = img.shape[:2]
            m = settings.preview_max_side
            if max(h, w) > m:
                scale = m / max(h, w)
                img = cv2.resize(img, (max(1, int(w * scale)), max(1, int(h * scale))),
                                 interpolation=cv2.INTER_AREA)
        img2 = store.img(s, image2_id) if image2_id else None

    _guard(spec, img)
    with t.phase("process"):
        try:
            res: OpResult = spec.run(OpContext(image=img, p=p, image2=img2,
                                               carry=s.carry, preview=preview, scale=scale))
        except OperationError:
            raise
        except cv2.error as exc:
            raise OperationError(f"{spec.cv} failed: {str(exc).splitlines()[-1]}",
                                 hint="Check channel count / dtype in the Inspector.") from exc

    out_img = res.image if res.image is not None else img
    with t.phase("store"):
        out_id = store.put(s, out_img)
        extras = {k: store.put(s, v) for k, v in res.extras.items()}

    metrics = t.as_dict()
    metrics["input_px"] = int(src.shape[0] * src.shape[1])
    entry = Entry(op_id=op_id, label=spec.label, params=p, image_id=out_id,
                  metrics=metrics, data=res.data, code=res.code, imports=res.imports,
                  summary=res.summary)
    if not preview:
        store.commit(s, entry)
        if res.carry:
            s.carry.update(res.carry)

    return {
        "ok": True, "preview": preview, "op": spec.to_json(), "params": p,
        "image_id": out_id, "extras": extras,
        "input": store.inspect(src), "output": store.inspect(out_img),
        "metrics": metrics, "data": res.data, "summary": res.summary,
        "notes": res.notes, "scale": scale,
        "code": generate_snippet(spec, res),
        "cursor": s.cursor, "history_len": len(s.history),
    }


def generate_snippet(spec: OpSpec, res: OpResult) -> str:
    body = "\n".join(res.code) if res.code else f"# {spec.cv}"
    return body


def generate_script(s: Session, upto: int | None = None) -> str:
    """Full runnable Python reproducing the committed pipeline."""
    end = s.cursor if upto is None else upto
    steps = s.history[1:end + 1]
    imports = {"import cv2", "import numpy as np"}
    for e in steps:
        imports.update(e.imports)
    lines = [
        '"""Generated by CV Dashboard — reproduces the pipeline exactly."""',
        *sorted(imports),
        "",
        'img = cv2.imread("input.jpg")   # BGR, uint8',
        'if img is None:',
        '    raise SystemExit("could not read input.jpg")',
        "",
    ]
    if not steps:
        lines.append("# (no operations applied yet)")
    for i, e in enumerate(steps, 1):
        lines.append(f"# --- step {i}: {e.label}  ({e.op_id}) ---")
        lines.extend(e.code or [f"# {e.op_id}"])
        lines.append("")
    lines += ['cv2.imwrite("output.png", img)']
    return "\n".join(lines)
